/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AutomatizacionReto;

public class Library {
    public boolean someLibraryMethod() {
        return true;
        
        
       
        
        
    }
}
